### ISSUE TITLE
rtr-address has no effect

### ISSUE THREAD

**Issue by dorpauli** [lolepezy/rpki-prover#73]
I tried to force rpki-prover to listen only on localhost with `--rtr-address localhost` but it's still reachable in the local network. I know that localhost is the deafult setting, But if the option is omitted rtr-server is still reachable from the local network.  

The same is the case for the API by the way. As far as i can see, there is no option for not listen to the external network interface.

**Comment by lolepezy** [comment]
Fixed with the commit
https://github.com/lolepezy/rpki-prover/commit/d5da64e0d8f7fae6ee9c47c8f6342f1154c10d78

I am inclined to gather a bit more changes before creating another release, unless you really need this 
feature to work. But if it's okay, you can build it from the `master` branch.

And thanks for reporting!
